{-# LANGUAGE OverloadedStrings #-}
module GenTuple(gen) where
import CUtil
import Names(contextArg)

import Text.PrettyPrint hiding ((<>))
-- Generate C code for tuple and PAp descriptors.
-- Includes both interface and implementation.

noFunc :: Code
noFunc = "NULL"

genTupleDesc :: Int -> Doc
genTupleDesc n =
  cCall "LING_MK_DESC" ["ling_tuples["<>int n<>"]", int n, noFunc, text $ show $ name n]
    where name 0 = "()"
          name 1 = "(_,)"
          name _ = "(" <> replicate (n-1) ',' <> ")"

genTuples :: Int -> Doc
genTuples n =
  sep [
    hsep ["const", "ling_desc", "ling_tuples["<>int (n+1)<>"]", equals, lbrace],
    cCommas (fmap genTupleDesc [0..n]),
    rbrace <> semi ]

genPApDesc :: Int -> Doc
genPApDesc n =
  cCall "LING_MK_DESC" ["ling_pAps[0][" <> int (n-1) <> "]",
                        int (n + 1), noFunc, text $ show ("pAp" <> show n)]

genPAps :: Int -> Doc
genPAps n =
  sep [
    hsep ["const", "ling_desc", "ling_pAps[1]["<>int n<>"]", equals, lbrace, lbrace],
    nest 2 $ fsep $ punctuate comma (fmap genPApDesc [1..n]),
    rbrace <> rbrace <> semi ]

genApply :: Int -> Doc
genApply n = do
  let
    args = [
      "ling_context" <+> ("*" <> pp contextArg),
      "ling_obj" <+> "clo",
      "const ling_obj" <+> "*args"]
    arm k = nest 2 $ vcat [
      hsep["case", int k, colon],
      nest 2 $ vcat[
        sep [
          "return",
          nest 2 $ sep[
            "(*(ling_obj (*)("<>cCommas ("ling_context *" : replicate k "ling_obj")<>"))f)",
            parens (cCommas (pp contextArg : ((\i -> hcat ["args[", int i, rbrack]) <$> [0..k-1])))<>semi]]]]
    body = vcat [
      "uintptr_t arity = clo.ref[1].uint_val;",
      "ling_obj (*f)() = clo.ref[2].func;",
      "switch (arity) {",
      vcat (fmap arm [1..n]),
      "  default: return ling_match_error(\"Arity too large in apply.  \");",
      "}"]
  vcat [
    hsep ["static", "ling_obj", "fapply"<>parens (cCommas args), lbrace],
    nest 2 body,
    rbrace]

gen :: IO ()
gen = do
  print (
    "/* GENERATED by GenTuple, do not edit */" $$
    "#include \"lingrts.h\"" $*$
    genTuples 32 $*$
    genPAps 31 $*$
    genApply 32)
