{-# LANGUAGE OverloadedStrings #-}
module GenTuple(gen) where
import CUtil
import Names(contextArg)

import Text.PrettyPrint hiding ((<>))
-- Generate C code for tuple and PAp descriptors.
-- Includes both interface and implementation.

genTupleDesc :: Int -> Doc
genTupleDesc n =
  cArray ["ling_tuples["<>int n<>"]", int n, "NULL", text $ show $ name n]
    where name 0 = "()"
          name 1 = "(_,)"
          name _ = "(" <> replicate (n-1) ',' <> ")"

genTuples :: Int -> Doc
genTuples n =
  sep [
    hsep ["const", "ling_desc", "ling_tuples["<>int (n+1)<>"]", lbrace],
    cCommas (fmap genTupleDesc [0..n]),
    rbrace <> semi ]

genPApDesc :: Int -> Doc
genPApDesc n =
  cArray ["ling_pAps[" <> int (n-1) <> "]",
          int n, "NULL", text $ show ("pAp" <> show n)]

genPAps :: Int -> Doc
genPAps n =
  sep [
    hsep ["const", "ling_desc", "ling_pAps["<>int n<>"]", lbrace],
    nest 2 $ fsep $ punctuate comma (fmap genPApDesc [1..n]),
    rbrace <> semi ]

genApply :: Int -> Doc
genApply n = do
  let
    args = [
      "ling_context" <+> ("*" <> pp contextArg),
      "ling_obj" <+> "clo",
      "int" <+> "nargs",
      "ling_obj" <+> "*args_in"]
    arm k = nest 4 $ vcat [
      hsep["case", int k, colon],
      nest 2 $ vcat[
        hcat[
          "clo = (*f)(",
          cCommas (pp contextArg : ((\i -> hcat ["args[", int i, rbrack]) <$> [1..k])),
          rparen],
        "break;" ]]
    body = vcat [
      "int pap_args;",
      "ling_obj *args = args_in;",
      "while (nargs > 0) {",
      "  ling_obj *clo_desc = clo[0];",
      -- Note: Relies on ling_pAps being a sized array to compute arity without lookup.
      "  if (ling_pAps <= clo_desc && clo_desc < ling_pAps + 1) {",
      "    int pap_arity = 1 + ((ling_desc *)clo_desc - (&ling_pAps[0])) : 0;",
      "    ling_obj *new_args = calloc((nargs + pap_arity) * sizeof(ling_obj));",
      "    memcpy(new_args, clo + 2, pap_args * sizeof(ling_obj));",
      "    memcpy(new_args, args, nargs * sizeof(ling_obj));",
      "    args = new_args;",
      "    nargs += pap_arity;",
      "    clo = clo[1];",
      "  }",
      "  ling_obj (*f)() = clo[2];",
      "  nargs -= clo[1];",
      "  switch (clo[1]) {",
      vcat (fmap arm [1..n]),
      "    default: return ling_match_error(\"Arity to large in apply\");",
      "  }",
      "}",
      "return clo;"]
  vcat [
    hsep ["ling_obj", "ling_apply"<>parens (cCommas args), lbrace],
    nest 2 body,
    rbrace]

gen :: IO ()
gen = do
  print (
    "/* GENERATED by GenTuple, do not edit */" $$
    "#include \"lingrts.h\"" $*$
    genTuples 32 $*$
    genPAps 31 $*$
    genApply 32)
